header:
  license:
    spdx-id: CC-BY-SA-4.0
    copyright-owner: by LunaSec (owned by Refinery Labs, Inc)
    content: |
      banana

  paths:
    - '*.md'
    - '**/*.md'
    - 'docs/*.{js,jsx,ts,tsx}'
    - 'docs/**/*.{js,jsx,ts,tsx}'
  paths-ignore:
    - 'docs/typedoc-sidebar.js'
    - 'docs/build/**'
    - 'docs/static/**'
    - 'docs/.docusaurus/**'
    - 'docs/pages/*.md'
    - 'docs/pages/**/*.md'
    - 'docs/*.json'
    - 'docs/**/*.json'
    - 'tools/license-checker/skywalking-*/**'
    - '**/node_modules/**'
    - 'pull_request_template.md'
    - 'topics'
  comment: on-failure

  license-location-threshold: 3000
