serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://localhost:4455/
  whitelisted_return_urls:
    - http://localhost:4455

  methods:
    password:
      enabled: false
    oidc:
      enabled: true
      config:
        providers:
          - id: github-oauth
            provider: github
            client_id: fake-value
            client_secret: another-fake-value
            mapper_url: file:///config/oidc.github.jsonnet
            scope:
              - user:email

  flows:
    error:
      ui_url: http://localhost:4455/api/kratos/error

    settings:
      ui_url: http://localhost:4455/api/kratos/settings
      privileged_session_max_age: 15m

    recovery:
      enabled: true
      ui_url: http://localhost:4455/api/kratos/recovery

    verification:
      enabled: true
      ui_url: http://localhost:4455/api/kratos/verification
      after:
        default_browser_return_url: http://localhost:4455/

    logout:
      after:
        default_browser_return_url: http://localhost:4455/api/kratos/login

    login:
      ui_url: http://localhost:4455/api/kratos/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://localhost:4455/api/kratos/registration
      after:
        password:
          hooks:
            -
              hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_url: file:///config/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
