table:
  name: affected_analysis_config
  schema: vulnerability
object_relationships:
  - name: affected
    using:
      foreign_key_constraint_on: affected_id
select_permissions:
  - role: cli
    permission:
      columns:
        - config
        - affected_id
        - id
      filter: {}
  - role: user
    permission:
      columns:
        - id
        - config
        - affected_id
      filter: {}
